### ISSUE TITLE
Slow start of PWM

### ISSUE THREAD

**Issue by HubertPOP** [ocrdu/Arduino_SAMD21_turbo_PWM#10]
Hi

Im running your turbo_PWM on a nano 33 IOT.
Im using it to control two steppermotors, running different frequencies and start/stop.
Also as PWM driving backlight on a display.
 
Issue is, it takes about 18 sec. before the PWM starts.
The rest of the code starts OK. Also when the PWM (after 18 sec.) starts, everything works great. 
Would you have any ideas what the problem is for the delayed start of PWM?

Code for steppers is like this:

#include <SAMD21turboPWM.h>

#define STEP 8

TurboPWM pwm;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);  

  for (int i= 0; i<= 5; i++) {
    delay(1000); 
    Serial.print("Serial init sec");
    Serial.println(i);
  }
 
  Serial.println("Debug");

  pinMode(STEP, OUTPUT);
  digitalWrite(STEP, LOW);

  pwm.setClockDivider(1, false); // Main clock 48 MHz divided by 1 => 48 MHz
  
  pwm.timer(0, 64, 14999, true); 

  pwm.analogWrite(STEP, 0); // 0/1000 dutycycle 
  pwm.analogWrite(STEP2, 0); // 0/1000 dutycycle
  

  // 
  analogReadResolution(12); 
    
  Serial.println("Debug after begin");

delay(1000);
  
}

void loop() {

  pwm.timer(0, 64, 14999, true); // 

  digitalWrite(DIR, LOW);
  digitalWrite(SLEEP, HIGH); // NOT sleep
  delay(2);
    
  pwm.analogWrite(STEP, 100); // start puls
    
  do {
    delay(1);       
    Serial.println(analogRead(A4)); // check what happens
} while (1);

**Comment by ocrdu** [comment]
Why do you initialise the timer and start the PWM over and over again in the loop? Also, your code does not compile.
