### ISSUE TITLE
Wrong index used in analogWrite

### ISSUE THREAD

**Issue by gh-scndml** [ocrdu/Arduino_SAMD21_turbo_PWM#12]
In analogWrite starting from line 134, wherever "pin" is used, "i" should be used instead. 
Currently (with the current pin tables) it does not make a difference, as (for all valid pins of a board) pin number and table index are the same. But in the general case, this might create a problem. 
Or we require always that pin number is the same as table index. Then we can remove the pin number from the struct and simplify the code (search loop not needed).

Best regards
gh-scndml

**Comment by ocrdu** [comment]
Pin number and table index should be the same, that's how the tables are designed. I wrote it like this to be able to take out the pin checks easily, as I don't use that code in my "own" version.
