### ISSUE TITLE
Add timer 5 for two more PWM pins at the nano IoT

### ISSUE THREAD

**Issue by silvan2468** [ocrdu/Arduino_SAMD21_turbo_PWM#13]
Hy

I also really like your library and I did right now some "improvement":
https://github.com/ocrdu/Arduino_SAMD21_turbo_PWM/issues/5

As describe there, with adding timer 5, it should be possible to have two more PWM pins on the Nano IoT!
And because these two pins also are interrupt supportet by arduino, they are two nice pins.

Thanks in advance for adding timer 5.

Kind regards
Silvan

**Comment by ocrdu** [comment]
Feel free to implement this, but I am not going to.
