### ISSUE TITLE
Unluck - I need PWM on Port 2 and 3 ...

### ISSUE THREAD

**Issue by ademmler** [ocrdu/Arduino_SAMD21_turbo_PWM#14]
Hello there,

I have carefully read your documentation and examples. And I am aware that you lib does not support D2 and D3 on Arduino Nano 33 IoT from scratch. Because my PCBs are already produced I have the unlucky situation that I 
have to use Pin 2,3,5,6 for PWM. I have tried to create my own pintable - see below. But it did not worked.

Would you or somebody help me - if possible - how to enable TurboPWM for this pins.

thx in advance

//Table begin
{-1, 0, 0, 0, 0, 0},
{-1, 0, 0, 0, 0, 0},
{ 2, PORTA, 10, 0, &REG_TCC0_CCB2, PORT_PMUX_PMUXE_E}, 
{ 3, PORTA, 11, 1, &REG_TCC1_CCB1, PORT_PMUX_PMUXO_E},
{-1, 0, 0, 0, 0, 0},
{ 5, PORTA, 5, 0, &REG_TCC0_CCB1, PORT_PMUX_PMUXO_E},
{ 6, PORTA, 4, 0, &REG_TCC0_CCB0, PORT_PMUX_PMUXE_E},
{-1, 0, 0, 0, 0, 0},
{-1, 0, 0, 0, 0, 0},
{-1, 0, 0, 0, 0, 0},
{-1, 0, 0, 0, 0, 0},
{11, PORTA, 16, 2, &REG_TCC2_CCB0, PORT_PMUX_PMUXE_E},
{-1, 0, 0, 0, 0, 0},
{13, PORTA, 17, 2, &REG_TCC2_CCB1, PORT_PMUX_PMUXO_E}
//Table end

**Comment by ocrdu** [comment]
There's a table under "extras" and a table in the datasheet of the SAMD21 that will help make a pin table for your needs. I am not going to make one for you.
