### ISSUE TITLE
SAMD21 

### ISSUE THREAD

**Issue by alaintanguy** [ocrdu/Arduino_SAMD21_turbo_PWM#15]
Can you make the program compatible with Adafruit QT PY SAMD21 ?
https://learn.adafruit.com/assets/110643
Thanks
Alain

**Comment by ocrdu** [comment]
See issue https://github.com/ocrdu/Arduino_SAMD21_turbo_PWM/issues/9.

It is perfectly doable; feel free to fork and add the QT Py.
