### ISSUE TITLE
Adafruit Feather M0 RFM69 Not working

### ISSUE THREAD

**Issue by Nathaniel-15** [ocrdu/Arduino_SAMD21_turbo_PWM#16]
I cannot seem to get the library to work on my Adafruit Feather M0 RFM69 board with the ATSAMD21G18 chip. I have tried the example code as well as my own code following the examples footsteps to a tee. Any and all help is greatly appreciated.

**Comment by ocrdu** [comment]
The examples assume a 33 IoT, pins will be different for other boards. Other than that, there's nowhere near enough information in your question to be able to help you.

**Comment by ocrdu** [comment]
The examples assume a 33 IoT, pins will be different for other boards. Other than that, there's nowhere near enough information in your question to be able to help you.
